"""Build a manuscript-ready evidence package from the frozen Step 31 result.

This is a read-only reporting stage.  It does not train or score a model,
change a threshold, rerun confirmation, invoke SUMO, or modify any existing
result.  It verifies the frozen evidence hashes and creates tables, figures,
claim/hypothesis matrices, limitations, reproducibility information, and
thesis/IEEE-SCI writing plans in one new timestamped directory.

Run from D:\\ztav_project::

    .\\.venv\\Scripts\\python.exe .\\src\\32_build_thesis_publication_package.py
"""

from __future__ import annotations

import csv
import hashlib
import json
import math
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
FINAL = RESULTS / "final_zero_trust_policy"
RUN_ID = datetime.now(timezone.utc).strftime("run_%Y%m%dT%H%M%S_%fZ")
OUT_ROOT = RESULTS / "thesis_scientific_publication_package"
OUT = OUT_ROOT / RUN_ID


FINAL_FILES = {
    "manifest": "final_policy_manifest.json",
    "primary": "final_primary_endpoint.csv",
    "external": "final_external_validation.csv",
    "claims": "final_claims_and_limitations.csv",
    "checks": "final_freeze_checks.csv",
    "components": "final_policy_components.csv",
    "evidence": "final_evidence_inventory.csv",
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: Iterable[dict[str, Any]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fields})


def as_bool(value: Any) -> bool:
    return str(value).strip().lower() in {"true", "1", "yes", "pass", "passed"}


def as_float(value: Any, default: float = math.nan) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def fmt(value: Any, digits: int = 4) -> str:
    number = as_float(value)
    if math.isnan(number):
        return "NA"
    return f"{number:.{digits}f}"


def pct(value: Any, digits: int = 2) -> str:
    number = as_float(value)
    if math.isnan(number):
        return "NA"
    return f"{100.0 * number:.{digits}f}%"


def latest(filename: str) -> Path:
    matches = [path for path in RESULTS.rglob(filename) if OUT_ROOT not in path.parents]
    if not matches:
        raise FileNotFoundError(f"Missing required publication evidence: {filename}")
    matches.sort(key=lambda path: (path.stat().st_mtime_ns, str(path)))
    return matches[-1]


def latex_escape(text: Any) -> str:
    value = str(text)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    return "".join(replacements.get(char, char) for char in value)


def make_primary_latex(rows: list[dict[str, Any]]) -> str:
    body = []
    for row in rows:
        body.append(
            "{} & {} & {} & {} & {} & {} \\\\".format(
                latex_escape(row["density_scenario"]),
                row["runs"],
                fmt(row["precision_mean"]),
                fmt(row["recall_mean"]),
                fmt(row["f1_mean"]),
                fmt(row["false_positive_rate_mean"]),
            )
        )
    return """% Generated by Step 32; verify journal formatting before submission.
\\begin{table}[t]
\\centering
\\caption{Frozen graded-policy in-domain endpoint by declared attack density.}
\\label{tab:primary_endpoint}
\\begin{tabular}{lrrrrr}
\\hline
Density & Runs & Precision & Recall & F1 & FPR \\\\
\\hline
""" + "\n".join(body) + """
\\hline
\\end{tabular}
\\end{table}
"""


def make_external_latex(rows: list[dict[str, Any]]) -> str:
    body = []
    for row in rows:
        body.append(
            "{} & {} & {} & {} \\\\".format(
                latex_escape(row["candidate"]),
                fmt(row["attack_recall"]),
                fmt(row["benign_fpr"]),
                latex_escape(row["publication_interpretation"]),
            )
        )
    return """% Generated by Step 32; negative external results must not be removed.
\\begin{table*}[t]
\\centering
\\caption{External validation and post-hoc diagnostic outcomes.}
\\label{tab:external_validation}
\\begin{tabular}{lrrp{7.2cm}}
\\hline
Candidate & Attack recall & Benign FPR & Interpretation \\\\
\\hline
""" + "\n".join(body) + """
\\hline
\\end{tabular}
\\end{table*}
"""


def build_plot(primary: list[dict[str, Any]], external: list[dict[str, Any]]) -> bool:
    try:
        import matplotlib.pyplot as plt
        import numpy as np
    except ImportError:
        return False

    labels = [row["density_scenario"] for row in primary]
    f1 = [as_float(row["f1_mean"]) for row in primary]
    fpr = [as_float(row["false_positive_rate_mean"]) for row in primary]
    can_recall = [as_float(row["can_injection_recall_mean"]) for row in primary]
    x = np.arange(len(labels))

    fig, axes = plt.subplots(1, 2, figsize=(15, 5.6))
    width = 0.25
    axes[0].bar(x - width, f1, width, label="End-to-end F1")
    axes[0].bar(x, can_recall, width, label="CAN-injection recall")
    axes[0].bar(x + width, fpr, width, label="Mean FPR")
    axes[0].axhline(0.90, color="green", linestyle="--", linewidth=1, label="F1 criterion")
    axes[0].axhline(0.05, color="red", linestyle=":", linewidth=1, label="FPR criterion")
    axes[0].set_xticks(x, labels, rotation=18, ha="right")
    axes[0].set_ylim(0, 1.05)
    axes[0].set_title("Frozen in-domain graded policy")
    axes[0].set_ylabel("Metric")
    axes[0].legend(fontsize=8)
    axes[0].grid(axis="y", alpha=0.25)

    ex_labels = [row["candidate"] for row in external]
    ex_recall = [as_float(row["attack_recall"]) for row in external]
    ex_fpr = [as_float(row["benign_fpr"]) for row in external]
    ex = np.arange(len(ex_labels))
    axes[1].bar(ex - 0.18, ex_recall, 0.36, label="Attack recall")
    axes[1].bar(ex + 0.18, ex_fpr, 0.36, label="Benign FPR")
    axes[1].axhline(0.80, color="green", linestyle="--", linewidth=1, label="External recall criterion")
    axes[1].axhline(0.05, color="red", linestyle=":", linewidth=1, label="FPR criterion")
    axes[1].set_xticks(ex, ex_labels, rotation=18, ha="right")
    axes[1].set_ylim(0, 1.05)
    axes[1].set_title("External evidence retained in final freeze")
    axes[1].set_ylabel("Metric")
    axes[1].legend(fontsize=8)
    axes[1].grid(axis="y", alpha=0.25)

    fig.suptitle("Multi-source context-aware Zero Trust research prototype", fontsize=15)
    fig.tight_layout()
    fig.savefig(OUT / "publication_main_results.png", dpi=220, bbox_inches="tight")
    plt.close(fig)
    return True


def main() -> None:
    if not FINAL.exists():
        raise FileNotFoundError("Step 31 output is missing. Run the authorized Step 31 freeze first.")
    paths = {key: FINAL / filename for key, filename in FINAL_FILES.items()}
    missing = [str(path) for path in paths.values() if not path.exists()]
    if missing:
        raise FileNotFoundError("Incomplete Step 31 output: " + "; ".join(missing))

    manifest = json.loads(paths["manifest"].read_text(encoding="utf-8-sig"))
    if manifest.get("freeze_ready") is not True:
        raise RuntimeError("Step 31 manifest is not freeze-ready.")
    if manifest.get("freeze_scope") != "bounded_research_prototype_freeze_only":
        raise RuntimeError("Unexpected freeze scope; refusing to generate publication claims.")
    if manifest.get("external_generalization_not_confirmed") is not True:
        raise RuntimeError("External-generalisation claim boundary is missing from the final manifest.")

    primary = read_csv(paths["primary"])
    external_raw = read_csv(paths["external"])
    final_claims = read_csv(paths["claims"])
    checks = read_csv(paths["checks"])
    components = read_csv(paths["components"])
    evidence = read_csv(paths["evidence"])
    if not primary or len(primary) != 4:
        raise RuntimeError("Expected four declared density endpoints in final_primary_endpoint.csv.")
    if any(not as_bool(row.get("passed")) for row in checks):
        raise RuntimeError("One or more final freeze checks are not passed.")

    hash_failures: list[str] = []
    reproducibility_rows: list[dict[str, Any]] = []
    for row in evidence:
        frozen_rel = row.get("frozen_copy", "")
        frozen_path = ROOT / frozen_rel if frozen_rel else None
        exists = bool(frozen_path and frozen_path.exists())
        observed_hash = sha256(frozen_path) if exists and frozen_path else ""
        expected_hash = row.get("sha256", "")
        matches = bool(exists and expected_hash and observed_hash == expected_hash)
        if not matches:
            hash_failures.append(row.get("evidence_key", "unknown"))
        reproducibility_rows.append({
            "evidence_key": row.get("evidence_key", ""),
            "purpose": row.get("purpose", ""),
            "frozen_copy": frozen_rel,
            "expected_sha256": expected_hash,
            "observed_sha256": observed_hash,
            "hash_verified": matches,
            "size_bytes": row.get("size_bytes", ""),
        })
    if hash_failures:
        raise RuntimeError("Frozen evidence hash verification failed: " + ", ".join(hash_failures))

    step30g_claims_path = latest("final_publication_claim_boundaries.csv")
    step30g_hypotheses_path = latest("final_hypothesis_verdicts.csv")
    statistics_path = latest("publication_statistical_summary.json")
    robustness_path = latest("source_robustness_summary.json")
    runtime_path = latest("publication_runtime_metrics.csv")
    resources_path = latest("publication_long_run_resource_metrics.csv")
    domain_shift_path = latest("gem_can_feature_domain_shift.csv")

    step30g_claims = read_csv(step30g_claims_path)
    hypotheses = read_csv(step30g_hypotheses_path)
    statistics = json.loads(statistics_path.read_text(encoding="utf-8-sig"))
    robustness = json.loads(robustness_path.read_text(encoding="utf-8-sig"))
    runtime = read_csv(runtime_path)
    resources = read_csv(resources_path)
    domain_shift = read_csv(domain_shift_path)

    primary_out: list[dict[str, Any]] = []
    for row in primary:
        primary_out.append({
            **row,
            "precision_percent": pct(row["precision_mean"]),
            "recall_percent": pct(row["recall_mean"]),
            "f1_percent": pct(row["f1_mean"]),
            "fpr_percent": pct(row["false_positive_rate_mean"]),
            "can_injection_recall_percent": pct(row["can_injection_recall_mean"]),
            "evidence_class": "in_domain_development_replay_frozen_endpoint",
        })

    external: list[dict[str, Any]] = []
    for row in external_raw:
        if "GEM-CAN" in row["candidate"]:
            interpretation = "Locked negative external confirmation; external generalisation not supported; no tuning or rerun."
        elif "Step 28" in row["candidate"]:
            interpretation = "Frozen ROAD zero-shot candidate failed its predeclared recall/FPR criteria."
        else:
            interpretation = "Post-hoc ROAD diagnostic/repair candidate excluded after failed readiness criteria."
        external.append({
            **row,
            "attack_recall_percent": pct(row["attack_recall"]),
            "benign_fpr_percent": pct(row["benign_fpr"]),
            "publication_interpretation": interpretation,
        })

    combined_runtime = next(
        row for row in runtime
        if row.get("method") == "w100_model_plus_graded_policy_runtime_path"
        and row.get("execution_mode") == "online_single_item"
    )
    policy_runtime = next(
        row for row in runtime
        if row.get("method") == "graded_multisource_policy_core"
        and row.get("execution_mode") == "online_single_item"
    )
    temporal_runtime = next(
        row for row in runtime
        if row.get("method") == "w20_temporal_micro_gate"
        and row.get("execution_mode") == "online_single_item"
    )
    resource_lookup = {
        (row.get("method"), row.get("execution_mode"), row.get("batch_size")): row
        for row in resources
    }
    efficiency_rows = []
    for label, row in [
        ("Combined frozen model plus policy", combined_runtime),
        ("Graded policy core", policy_runtime),
        ("Temporal micro-gate", temporal_runtime),
    ]:
        resource = resource_lookup.get((row.get("method"), row.get("execution_mode"), row.get("batch_size")), {})
        efficiency_rows.append({
            "component": label,
            "method": row.get("method"),
            "median_ms_per_item": row.get("wall_latency_median_ms"),
            "p95_ms_per_item": row.get("wall_latency_p95_ms"),
            "p99_ms_per_item": row.get("wall_latency_p99_ms"),
            "long_run_ms_per_item": resource.get("long_run_wall_time_per_item_ms", ""),
            "long_run_throughput_items_per_second": resource.get("long_run_throughput_items_per_second", ""),
            "process_rss_peak_mb": resource.get("long_run_process_rss_peak_mb", ""),
            "scope_limitation": "Engineered/recorded evidence only; acquisition, transport, raw parsing, feature extraction, SUMO runtime and ECU deployment excluded.",
        })

    domain_shift.sort(key=lambda row: as_float(row.get("absolute_standardized_mean_shift")), reverse=True)
    top_shift = domain_shift[:5]
    min_f1_row = min(primary, key=lambda row: as_float(row["f1_mean"]))
    max_fpr_row = max(primary, key=lambda row: as_float(row["false_positive_rate_mean"]))
    low_row = next(row for row in primary if row["density_scenario"] == "low_1_5")
    representative_row = next(row for row in primary if row["density_scenario"] == "representative_all")
    gem_row = next(row for row in external if "GEM-CAN" in row["candidate"])
    road_row = next(row for row in external if "Step 28" in row["candidate"])

    OUT.mkdir(parents=True, exist_ok=False)
    write_csv(
        OUT / "publication_core_metrics.csv",
        primary_out,
        list(primary_out[0].keys()),
    )
    write_csv(
        OUT / "publication_external_validation.csv",
        external,
        list(external[0].keys()),
    )
    write_csv(
        OUT / "publication_claim_matrix.csv",
        step30g_claims,
        ["claim_id", "statement", "evidence_status", "publication_permission", "required_wording"],
    )
    write_csv(
        OUT / "publication_hypothesis_matrix.csv",
        hypotheses,
        ["hypothesis", "final_status", "confirmatory", "publication_interpretation"],
    )
    write_csv(
        OUT / "publication_efficiency_summary.csv",
        efficiency_rows,
        ["component", "method", "median_ms_per_item", "p95_ms_per_item", "p99_ms_per_item", "long_run_ms_per_item", "long_run_throughput_items_per_second", "process_rss_peak_mb", "scope_limitation"],
    )
    write_csv(
        OUT / "publication_reproducibility_manifest.csv",
        reproducibility_rows,
        ["evidence_key", "purpose", "frozen_copy", "expected_sha256", "observed_sha256", "hash_verified", "size_bytes"],
    )
    write_csv(
        OUT / "publication_top_gem_can_domain_shifts.csv",
        top_shift,
        ["feature", "training_mean", "training_std", "gem_can_mean", "standardized_mean_shift", "absolute_standardized_mean_shift"],
    )

    (OUT / "TABLE_1_PRIMARY_ENDPOINT.tex").write_text(make_primary_latex(primary), encoding="utf-8")
    (OUT / "TABLE_2_EXTERNAL_VALIDATION.tex").write_text(make_external_latex(external), encoding="utf-8")

    results_draft = f"""# Results narrative draft

Use this as a factual starting point, then adapt it to the target journal's style.
Do not remove the negative results or broaden the claim boundaries.

## Frozen in-domain endpoint

Across the four declared density scenarios, the frozen graded policy produced
mean end-to-end F1 values from {fmt(min_f1_row['f1_mean'])}
({min_f1_row['density_scenario']}) to
{fmt(max(primary, key=lambda row: as_float(row['f1_mean']))['f1_mean'])}.
The largest mean false-positive rate was {fmt(max_fpr_row['false_positive_rate_mean'])}
({max_fpr_row['density_scenario']}), below the predeclared 0.05 operating limit.
These are frozen in-domain CICIoV-SUMO replay endpoints and are not external
vehicle-deployment results.

CAN-injection recall was density dependent. It was
{fmt(low_row['can_injection_recall_mean'])} for low_1_5 and
{fmt(representative_row['can_injection_recall_mean'])} for representative_all.
Accordingly, the low-density limitation must be presented separately from the
high aggregate end-to-end F1.

## Statistical and source-robustness interpretation

The Step 30B H1 assessment was
`{statistics.get('h1_development_assessment')}`; therefore improvement must not
be claimed across every density. H2 was
`{statistics.get('h2_development_assessment')}` within the in-domain development
protocol, while H3 was `{statistics.get('h3_development_assessment')}` and is
descriptive. Step 30C assessed H4 as
`{robustness.get('h4_development_assessment')}` and H5 as
`{robustness.get('h5_development_assessment')}`. Detected-compromise claims are
conditional on observable integrity/conflict evidence; universal protection
against an undetected false-healthy Byzantine source is not supported.

## External validation

The frozen ROAD zero-shot candidate achieved attack recall
{fmt(road_row['attack_recall'])} with benign FPR {fmt(road_row['benign_fpr'])}
and failed its predeclared criteria. The one-time locked GEM-CAN confirmation
achieved high-density cluster-macro recall {fmt(gem_row['attack_recall'])} and
clean cluster-macro FPR {fmt(gem_row['benign_fpr'])}. The GEM-CAN model,
threshold, window definition, and protocol were not changed after observing the
result. This is a valid negative external confirmation and bounds the method's
cross-vehicle/CAN-schema transfer claim.

The largest GEM-CAN standardized feature shift was
`{top_shift[0].get('feature')}` (absolute shift
{fmt(top_shift[0].get('absolute_standardized_mean_shift'), 3)}), supporting a
domain-shift interpretation rather than post-hoc threshold tuning.

## Computational scope

For the combined frozen model-plus-policy runtime path, the measured warm
median/p95/p99 latency was
{fmt(combined_runtime.get('wall_latency_median_ms'), 6)}/
{fmt(combined_runtime.get('wall_latency_p95_ms'), 6)}/
{fmt(combined_runtime.get('wall_latency_p99_ms'), 6)} ms per item. These values
cover inference and policy logic over engineered/recorded evidence. They exclude
raw CAN parsing, feature extraction, sensor acquisition, network transport,
SUMO execution, and embedded ECU deployment.
"""
    (OUT / "RESULTS_NARRATIVE_DRAFT.md").write_text(results_draft, encoding="utf-8")

    limitations = """# Limitations and threats to validity

## Internal validity

- The strong primary endpoint is based on the frozen CICIoV-SUMO replay protocol.
- H1 was not supported across every density; H4 and the universal H5 claim failed.
- The primary vehicle-state score was excluded after counterfactual falsification.
- Window-level pseudoreplication was avoided in the publication statistical analysis, but the number of independent seeds/captures still limits inference.

## Construct validity

- The Zero Trust actions are research-policy outputs, not commands validated on a safety-certified vehicle controller.
- The SUMO-derived context represents GNSS/V2X/identity/operational evidence in replay, not a complete physical sensor and network stack.
- Efficiency measurements exclude acquisition, network transport, raw parsing, feature extraction, SUMO runtime, and ECU integration.

## External validity

- Frozen ROAD transfer failed its predeclared criteria.
- Locked GEM-CAN high-density external recall was 0.0; no low/medium or family-specific GEM-CAN claim is permitted.
- The results do not establish universal transfer across vehicles, CAN schemas, attacks, road environments, or hardware platforms.

## Conclusion validity

- Density-specific outcomes must be reported; aggregate F1 must not hide low-density CAN recall.
- Failed and unsupported hypotheses are retained rather than relabelled after inspection.
- No threshold/model/window tuning or GEM-CAN rerun is permitted after the one-time confirmation.

## Deployment and safety boundary

- This is a bounded research prototype, not production automotive security software.
- No functional-safety, cybersecurity-certification, real-time schedulability, fail-operational, or closed-track/road validation claim is supported.
"""
    (OUT / "LIMITATIONS_AND_THREATS_TO_VALIDITY.md").write_text(limitations, encoding="utf-8")

    thesis_plan = f"""# Master's thesis chapter plan

## Proposed thesis title

**A Multi-Source Context-Aware Zero Trust Security Method for Self-Driving Vehicle Systems**

## Chapter 1 — Introduction

- Motivation: heterogeneous and safety-relevant attack surfaces in automated vehicles.
- Problem: CAN-only detection is vulnerable to domain shift and sparse attacks.
- Research question: how can multiple context sources support graded Zero Trust decisions without implicitly trusting one source?
- Contributions: leakage-safe CAN pipeline, multi-source context fusion, graded actions, falsification audits, and bounded external validation.

## Chapter 2 — Background and related work

- In-vehicle networks and CAN attacks.
- Intrusion detection for connected/autonomous vehicles.
- Zero Trust principles and continuous verification.
- Multi-source context, V2X, GNSS, identity, and device posture.
- Research gap and comparison table. Add current peer-reviewed references manually; Step 32 does not invent citations.

## Chapter 3 — Threat model and requirements

- Assets, trust boundaries, adversaries, and attack capabilities.
- Observable versus undetected false-healthy source compromise.
- Security, availability, latency, and safety constraints.
- Explicit prohibited claims and prototype boundary.

## Chapter 4 — Proposed method

- Group-disjoint CAN evidence model.
- Session-normalized and temporal sparse-CAN gates.
- GNSS, V2X, identity, device-posture, and operational context.
- Continuous trust calculation and graded actions: ALLOW, VERIFY, RESTRICT, SAFE_FALLBACK.
- Startup consistency guard and source-observability assumptions.

## Chapter 5 — Experimental methodology

- CICIoV2024 preparation and leakage-safe feature grouping.
- SUMO context experiments and controlled attacks.
- ROAD and GEM-CAN external datasets.
- Development/confirmation separation, predeclared criteria, seeds, bootstrap CIs, and paired analysis.
- Hardware and efficiency-measurement scope.

## Chapter 6 — Results

- Frozen primary endpoint: minimum F1 {fmt(min_f1_row['f1_mean'])}; maximum mean FPR {fmt(max_fpr_row['false_positive_rate_mean'])}.
- Density sensitivity: low-density CAN recall {fmt(low_row['can_injection_recall_mean'])}.
- H1/H4/H5 outcomes and source-observability boundary.
- ROAD and GEM-CAN negative external results.
- Computational performance and resource measurements.

## Chapter 7 — Discussion

- Why multi-source policy evidence improves end-to-end decisions in-domain.
- Why CAN-only transfer fails under domain shift.
- Security–availability trade-offs and conditional source-compromise handling.
- Comparison with related work without claiming universal superiority.

## Chapter 8 — Limitations, future work, and conclusion

- External validity and real-vehicle evaluation needs.
- Online domain adaptation without confirmation leakage.
- Hardware-in-the-loop and closed-track testing.
- Safety assurance, explainability, and adversarial source-quality estimation.
"""
    (OUT / "THESIS_CHAPTER_PLAN.md").write_text(thesis_plan, encoding="utf-8")

    paper_plan = """# IEEE/SCI manuscript plan

## Working title

**Multi-Source Context-Aware Zero Trust Enforcement for Self-Driving Vehicle Security: A Falsification-Driven Evaluation**

## Abstract structure

1. Problem and gap (2 sentences).
2. Proposed multi-source Zero Trust method (2 sentences).
3. Datasets/protocol and leakage controls (1–2 sentences).
4. Density-specific primary findings (2 sentences).
5. Negative ROAD/GEM-CAN and source-robustness findings (2 sentences).
6. Bounded conclusion—research prototype, not production validation (1 sentence).

## Main sections

1. Introduction and contributions.
2. Related work.
3. Threat model and Zero Trust design.
4. Method and policy architecture.
5. Experimental protocol and statistical analysis.
6. Results.
7. Falsification, external validation, and limitations.
8. Discussion and conclusion.

## Required main-paper tables/figures

- Architecture diagram showing evidence sources, trust fusion, policy actions, and safe fallback.
- Dataset/protocol table with development and confirmation roles.
- Primary density-specific endpoint table.
- H1–H5 hypothesis/claim-boundary table.
- External ROAD/GEM-CAN results table.
- Runtime/resource table with scope exclusions.
- Main in-domain versus external evidence figure.

## Reporting rules

- Use run/capture/cluster-level units exactly as recorded.
- Report confidence intervals and adjusted p-values where available.
- Separate development, descriptive, and confirmatory evidence.
- Retain all failed tests and negative external results.
- Never describe the prototype as production-ready or safety-certified.
"""
    (OUT / "IEEE_SCI_MANUSCRIPT_PLAN.md").write_text(paper_plan, encoding="utf-8")

    checklist = [
        {"item": "Frozen evidence hashes verified", "status": "complete", "owner_action": "none"},
        {"item": "Primary and external result tables generated", "status": "complete", "owner_action": "format for target venue"},
        {"item": "Claims and hypotheses bounded", "status": "complete", "owner_action": "retain wording in manuscript"},
        {"item": "Limitations and threats to validity drafted", "status": "complete", "owner_action": "adapt to university/journal style"},
        {"item": "Current peer-reviewed literature review", "status": "pending", "owner_action": "select and verify references"},
        {"item": "Target SCI/IEEE venue selected", "status": "pending", "owner_action": "check scope, template, page limit and data policy"},
        {"item": "University thesis template applied", "status": "pending", "owner_action": "obtain official template"},
        {"item": "Supervisor review and authorship approval", "status": "pending", "owner_action": "schedule formal review"},
        {"item": "Dataset/code licences documented", "status": "pending", "owner_action": "verify redistribution and citation terms"},
        {"item": "Language, similarity and ethics checks", "status": "pending", "owner_action": "complete before submission"},
    ]
    write_csv(OUT / "SUBMISSION_READINESS_CHECKLIST.csv", checklist, ["item", "status", "owner_action"])

    plot_saved = build_plot(primary, external)
    output_files = sorted(path for path in OUT.iterdir() if path.is_file())
    package_manifest = {
        "stage": "32",
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "source_policy_id": manifest.get("policy_id"),
        "source_policy_status": manifest.get("policy_status"),
        "freeze_scope": manifest.get("freeze_scope"),
        "frozen_evidence_files_verified": len(reproducibility_rows),
        "frozen_evidence_hash_failures": 0,
        "external_generalization_confirmed": False,
        "universal_source_robustness_confirmed": False,
        "production_or_safety_certification_permitted": False,
        "plot_saved": plot_saved,
        "generated_files": [path.name for path in output_files],
        "python": sys.version,
    }
    (OUT / "publication_package_manifest.json").write_text(json.dumps(package_manifest, indent=2), encoding="utf-8")
    archive = Path(shutil.make_archive(str(OUT_ROOT / f"thesis_scientific_publication_package_{RUN_ID}"), "zip", root_dir=OUT))

    print("=" * 78)
    print("Step 32 thesis/SCI publication evidence package completed successfully.")
    print("Existing project artifacts changed: 0")
    print(f"Frozen evidence hashes verified: {len(reproducibility_rows)}/{len(reproducibility_rows)}")
    print(f"Primary density endpoints exported: {len(primary)}")
    print(f"External candidates exported: {len(external)}")
    print(f"Claim boundaries exported: {len(step30g_claims)}")
    print(f"Hypothesis verdicts exported: {len(hypotheses)}")
    print("External generalisation confirmed: False")
    print("Production/safety-certification claim permitted: False")
    print(f"Results directory: {OUT}")
    print(f"Publication package: {archive}")
    print("\nNext: send the Step 32 terminal result and publication-package ZIP for manuscript drafting.")


if __name__ == "__main__":
    main()
